### ISSUE TITLE
求解步骤出现问题，之前进不去代理，通过问题解决了，但是求解步骤进不去

### ISSUE THREAD

**Issue by 351535126** [NB-Dragon/SheepSolver#23]
PS C:\Users\33885\Desktop\NB> python solve.py -m normal
Traceback (most recent call last):
  File "C:\Users\33885\Desktop\NB\solve.py", line 25, in <module>
    sheep_solver = SheepSolver(solve_mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\33885\Desktop\NB\business\SheepSolver.py", line 13, in __init__
    self._project_helper = ProjectHelper()
                           ^^^^^^^^^^^^^^^
  File "C:\Users\33885\Desktop\NB\hepler\ProjectHelper.py", line 12, in __init__
    self._code_entrance_path = self._get_project_path()
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\33885\Desktop\NB\hepler\ProjectHelper.py", line 49, in _get_project_path
    class_save_path = os.path.split(os.path.abspath(script_path))[0]
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 580, in abspath
  File "<frozen ntpath>", line 547, in normpath
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by 351535126** [comment]
不能改名字，改回来就行了。
